# Git Aliases
alias gco='git checkout'
alias ga='git add'
alias gcm='git commit -m'
alias gst='git status'
alias gr='git rebase'
alias gb='git branch'
alias gp='git pull'
alias gl='git log'
alias gpu='git push'
